import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import obfuscator from "rollup-plugin-obfuscator";
import react from "@vitejs/plugin-react";
import tsconfigPaths from 'vite-tsconfig-paths';


let fonts = [
    "resources/fonts/dripicons-v2.eot",
    "resources/fonts/dripicons-v2.svg",
    "resources/fonts/dripicons-v2.ttf",
    "resources/fonts/dripicons-v2.woff",
    "resources/fonts/fa-brands-400.eot",
    "resources/fonts/fa-brands-400.svg",
    "resources/fonts/fa-brands-400.ttf",
    "resources/fonts/fa-brands-400.woff",
    "resources/fonts/fa-brands-400.woff2",
    "resources/fonts/fa-regular-400.eot",
    "resources/fonts/fa-regular-400.svg",
    "resources/fonts/fa-regular-400.ttf",
    "resources/fonts/fa-regular-400.woff",
    "resources/fonts/fa-regular-400.woff2",
    "resources/fonts/fa-solid-900.eot",
    "resources/fonts/fa-solid-900.svg",
    "resources/fonts/fa-solid-900.ttf",
    "resources/fonts/fa-solid-900.woff",
    "resources/fonts/fa-solid-900.woff2",
    "resources/fonts/materialdesignicons-webfont.eot",
    "resources/fonts/materialdesignicons-webfont.ttf",
    "resources/fonts/materialdesignicons-webfont.woff",
    "resources/fonts/materialdesignicons-webfont.woff2",
    "resources/fonts/summernote.eot",
    "resources/fonts/summernote.ttf",
    "resources/fonts/summernote.woff",
    "resources/fonts/themify.eot",
    "resources/fonts/themify.svg",
    "resources/fonts/themify.ttf",
    "resources/fonts/themify.woff",
    "resources/fonts/typicons.css",
    "resources/fonts/typicons.eot",
    "resources/fonts/typicons.min.css",
    "resources/fonts/typicons.svg",
    "resources/fonts/typicons.ttf",
    "resources/fonts/typicons.woff",
];
let base_scss = [
    "resources/css/app-dark.scss",
    "resources/css/app.scss",
    "resources/css/bootstrap-dark.scss",
    "resources/css/bootstrap.scss",
    "resources/css/icons.scss",
];

let js = [
    "resources/js/app.js",
    "resources/js/achats_create.js",
    "resources/js/achats_liste.js",
    "resources/js/article_create.js",
    "resources/js/article_index.js",
    "resources/js/clients_liste.js",
    "resources/js/vente_create.js",
    "resources/js/inventaire_create.js",
    "resources/js/ventes_liste.js",
    "resources/js/article_modal.js",
    "resources/js/documents_parameters.js",
    "resources/js/affaires_create.js",
    "resources/js/compte_show.js",
    "resources/js/affaire_afficher.js",
    "resources/js/cheques_encaisser.js",
    "resources/js/cheques_decaisser.js",
    'resources/js/parametres/woocommerce_liste.js',
    'resources/js/importations/woocommerce.js',
    'resources/js/transformations/ajouter.js',
    'resources/js/rebuts_create.js',
];

let reactComponents = [
    "resources/pos/main.tsx",
    "resources/pos/app/app.css",
    "resources/js/components/pages/PosParfums.jsx",
    "resources/js/components/pages/PosCommercial.jsx",
    "resources/js/components/pages/PosClassic.jsx",
    "resources/js/components/pages/PosCaisse.jsx",
    "resources/js/components/pages/Demandes.jsx",
];
export default defineConfig({
    plugins: [
        laravel({
            input: [...fonts, ...base_scss, ...js, ...reactComponents],
            refresh: true,
        }),
        tsconfigPaths(),
        react(),
        obfuscator({
            options: {
                compact: true,
                controlFlowFlattening: true,
                controlFlowFlatteningThreshold: 0.75,
                deadCodeInjection: false,
                deadCodeInjectionThreshold: 0.4,
                debugProtection: false,
                debugProtectionInterval: 0,
                disableConsoleOutput: false,
                domainLock: [],
                domainLockRedirectUrl: "about:blank",
                forceTransformStrings: [],
                identifierNamesCache: null,
                identifierNamesGenerator: "mangled-shuffled",
                identifiersDictionary: [],
                identifiersPrefix: "gero",
                ignoreImports: false,
                inputFileName: "",
                log: false,
                numbersToExpressions: false,
                optionsPreset: "medium-obfuscation",
                renameGlobals: false,
                renameProperties: false,
                renamePropertiesMode: "safe",
                reservedNames: [],
                reservedStrings: [],
                seed: 0,
                selfDefending: false,
                simplify: true,
                sourceMap: false,
                sourceMapBaseUrl: "",
                sourceMapFileName: "",
                sourceMapMode: "separate",
                sourceMapSourcesMode: "sources-content",
                splitStrings: false,
                splitStringsChunkLength: 10,
                stringArray: true,
                stringArrayCallsTransform: true,
                stringArrayCallsTransformThreshold: 0.75,
                stringArrayEncoding: ["base64"],
                stringArrayIndexesType: ["hexadecimal-number"],
                stringArrayIndexShift: true,
                stringArrayRotate: true,
                stringArrayShuffle: true,
                stringArrayWrappersCount: 1,
                stringArrayWrappersChainedCalls: true,
                stringArrayWrappersParametersMaxCount: 2,
                stringArrayWrappersType: "variable",
                stringArrayThreshold: 0.75,
                target: "browser",
                transformObjectKeys: false,
                unicodeEscapeSequence: false,
            },
        }),
    ],
    build: {
        commonjsOptions: { transformMixedEsModules: true },
    },
    resolve: {
        alias: [],
    },
});
